# This config file is used by ros2_control


mujoco_ros2_control_node:
  ros__parameters:
    mujoco_plugins:
      object_sync_plugin:
        type: "h1_2_mujoco_plugins/ObjectSyncPlugin"

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    mujoco_plugins:
      object_sync_plugin:
        type: "h1_2_mujoco_plugins/ObjectSyncPlugin"

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - left_wrist_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 3.0
      stopped_velocity_tolerance: 0.20
      left_shoulder_pitch_joint:
        trajectory: 0.25
        goal: 0.08
      left_shoulder_roll_joint:
        trajectory: 0.25
        goal: 0.08
      left_shoulder_yaw_joint:
        trajectory: 0.25
        goal: 0.08
      left_elbow_joint:
        trajectory: 0.25
        goal: 0.08
      left_wrist_roll_joint:
        trajectory: 0.25
        goal: 0.08
      left_wrist_pitch_joint:
        trajectory: 0.25
        goal: 0.08
      left_wrist_yaw_joint:
        trajectory: 0.25
        goal: 0.08
right_arm_controller:
  ros__parameters:
    joints:
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
      - right_wrist_roll_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 3.0
      stopped_velocity_tolerance: 0.20
      right_shoulder_pitch_joint:
        trajectory: 0.25
        goal: 0.08
      right_shoulder_roll_joint:
        trajectory: 0.25
        goal: 0.08
      right_shoulder_yaw_joint:
        trajectory: 0.25
        goal: 0.08
      right_elbow_joint:
        trajectory: 0.25
        goal: 0.08
      right_wrist_roll_joint:
        trajectory: 0.25
        goal: 0.08
      right_wrist_pitch_joint:
        trajectory: 0.25
        goal: 0.08
      right_wrist_yaw_joint:
        trajectory: 0.25
        goal: 0.08
      
left_hand_controller:
  ros__parameters:
    joints:
      - L_index_proximal_joint
      - L_middle_proximal_joint
      - L_pinky_proximal_joint
      - L_ring_proximal_joint
      - L_thumb_proximal_yaw_joint
      - L_thumb_proximal_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_hand_controller:
  ros__parameters:
    joints:
      - R_index_proximal_joint
      - R_middle_proximal_joint
      - R_pinky_proximal_joint
      - R_ring_proximal_joint
      - R_thumb_proximal_yaw_joint
      - R_thumb_proximal_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

torso_controller:
  ros__parameters:
    joints:
      - torso_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
